print("This is first line of main branch".)
print("This is project is under open source projects.")
print("Sky has beautiful clouds today.")
print("This is first line of branch1.")
print("Today's date is 2nd December 2023.")
